name: live_demo
channels:
  - conda-forge
dependencies:
  - python
  - dask
  - cf_xarray
  - numpy
  - gcsfs
  - fsspec
  - intake-esm
  - matplotlib
  - xarray
  - nc-time-axis
  - xarrayutils>=2.0.1
  - zarr
  - xmip
  - xarray-datatree
