name: live_demo
channels:
  - conda-forge
dependencies:
  - python
  - dask
  - numpy
  - pip
  - gcsfs
  - fsspec
  - intake-esm
  - xarray
  - xarrayutils
  - zarr
  - pip:
    - xmip
    - xarray-datatree